apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: quarkus-vulnerable-app-build-
spec:
  serviceAccountName: pipeline
  pipelineRef:
    name: quarkus-vulnerable-app-build
  params:
    - name: git-url
      value: https://github.com/le0nard01/ai-security-workflow.git
    - name: git-revision
      value: main
    - name: destination-image
      value: image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/quarkus-vuln-demo:latest
    - name: hardened-runtime-image
      value: registry.access.redhat.com/hi/openjdk:latest-runtime
    - name: builder-image
      value: registry.access.redhat.com/ubi9/openjdk-17:latest
    - name: rox-central-endpoint
      value: central.rhacs-operator.svc.cluster.local:443
    - name: rox-api-token-secret
      value: rox-api-token
    - name: rox-insecure-skip-tls-verify
      value: true
    - name: roxctl-image
      value: registry.redhat.io/advanced-cluster-security/rhacs-roxctl-rhel8:4.10

  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi