ARG BUILDER_IMAGE=registry.access.redhat.com/ubi9/openjdk-17:latest
ARG RUNTIME_IMAGE=registry.access.redhat.com/hi/openjdk:latest-runtime

FROM ${BUILDER_IMAGE} AS build

WORKDIR /workspace

COPY pom.xml .
COPY src ./src

RUN mvn -B package -DskipTests

FROM ${RUNTIME_IMAGE} AS runtime

WORKDIR /work/

COPY --from=build /workspace/target/quarkus-app/lib/ /work/lib/
COPY --from=build /workspace/target/quarkus-app/*.jar /work/
COPY --from=build /workspace/target/quarkus-app/app/ /work/app/
COPY --from=build /workspace/target/quarkus-app/quarkus/ /work/quarkus/

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/work/quarkus-run.jar"]
